version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - habsat_network
    volumes:
      - habsat_postgres:/var/lib/postgresql/data
      - ./.postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  aws:
    image: localstack/localstack:latest
    container_name: aws
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      USE_SSL: 0
      SERVICES: 's3'
      EDGE_PORT: 4566
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
    ports:
      - '4563-4599:4563-4599'
    networks:
      - habsat_network
    volumes:
      - habsat_aws:/tmp/localstack
      - ./.aws/docker-entrypoint-initaws.d:/docker-entrypoint-initaws.d

networks:
  habsat_network: null

volumes:
  habsat_postgres: null
  habsat_aws: null