spring:
  cloud:
    gateway:
      routes:
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path= /email-service/**
      discovery:
        locator:
          enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
