
spring:
  application:
    name: 'user-service'
  datasource:
    password: 'habsat'
    username: 'habsat'
    url: 'jdbc:postgresql://146.59.17.124:5432/db'
  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    livereload:
      enabled: true
server:
  error:
    include-message: always
    include-stacktrace: never
  port: 8050
  servlet:
    context-path: '/user-service'
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}