spring:
  application:
    name: 'authorization-server'
  data:
    mongodb:
      host: 'localhost'
      port: 27017
      database: 'session'
server:
  port: 1234
  servlet:
    context-path: '/auth'